server:
  port: 8889

spring.mvc.servlet.path: /admin
eureka.instance.ip-address: 172.16.3.3
    
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JinHo1Lee/spring-micro-service.git

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.ip-address:localhost}:${eureka.port:8761}/eureka/